name: Seat Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  # 매 5분마다 실행 (UTC 기준)
  workflow_dispatch:       # 수동 실행도 가능하게 설정

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run seat_num.py
        run: python seat_num.py
